### ISSUE TITLE
fix for APOS_SECOND possessive noun (eg: o'brien's)

### ISSUE THREAD

**Issue by pfaulks** [ppannuto/python-titlecase#10]
#APOS_SECOND = re.compile(r"^[dol]{1}['â€˜]{1}[a-z]+$", re.I)
APOS_SECOND = re.compile(r"^[dol]{1}['â€˜]{1}[a-z]+(?:['s]{2})?$", re.I)   # fix for possessive noun

**Comment by ppannuto** [comment]
Thanks for the patch, could you give me a few example sentences that this
is fixing? I like to add them to test cases to make sure I don't mess
things up later.

Thanks!
