### ISSUE TITLE
When hyphens are used as colons, e.g. "snakes on a plane - the tv edit - the famous line"

### ISSUE THREAD

**Issue by HatScripts** [ppannuto/python-titlecase#13]
The example given results in:
```
Failure
Expected :'Snakes on a Plane - The TV Edit - The Famous Line'
Actual   :'Snakes on a Plane - the Tv Edit - the Famous Line'
```
In a title, when a hyphen has a space on either side of it (" - "), it is basically taking the role of a colon (as commonly seen in filenames). Thus the word following it should be capitalised. Would you agree?

In another note, I noticed that "tv" isn't automatically capitalised to "TV". Perhaps a check could be implemented to capitalise common all-caps acronyms/initialisms such as TV, ATM, IQ, NASA, [etc](http://www.enchantedlearning.com/acronyms/). I understand if that's asking for too much, or if you feel that such a feature would be too far outside the scope of this function's purpose. So on that note, is there a way I could set the uppercase word list myself, similar to the way you can specify your own small word list by calling `set_small_word_list`?

**Comment by ppannuto** [comment]
On Wed, Nov 11, 2015 at 2:50 AM Nick <notifications@github.com> wrote:

> The example given results in:
>
> Failure
> Expected :'Snakes on a Plane - The TV Edit - The Famous Line'
> Actual   :'Snakes on a Plane - the Tv Edit - the Famous Line'
>
> In a title, when a hyphen has a space on either side of it (" - "), it is
> basically taking the role of a colon (as commonly seen in filenames). Thus
> the word following it should be capitalised. Would you agree?
>
Yeah, that would be a nice improvement.

> In another note, I noticed that "tv" isn't automatically capitalised to
> "TV". Perhaps a check could be implemented to capitalise common all-caps
> acronyms/initialisms such as TV, ATM, IQ, NASA, etc
> <http://www.enchantedlearning.com/acronyms/>. I understand if that's
> asking for too much, or if you feel that such a feature would be too far
> outside the scope of this function's purpose. So on that note, is there a
> way I could set the uppercase word list myself, similar to the way you can
> specify your own small word list by calling set_small_word_list?
>
Yeah, something like an acronym_list or always_caps list would also be a
good addition.

I'm happy to take pull requests for either or both of these, but I probably
won't have time to implement them any time soon

**Comment by HatScripts** [comment]
Thanks for the response. The reason I didn't make a pull request for these outright is that I'm quite new to programming in Python. My first project just happened to involve needing to make a string be title-cased. For now I'll use the method as-is without trying to implement those suggestions.
