### ISSUE TITLE
Fails on spanish words with accents

### ISSUE THREAD

**Issue by alexvicegrab** [ppannuto/python-titlecase#17]
Hi,

When I try to use the titlecase and provide it with a spanish word like "Señor", because of the letter n and tilde representation, it returns:
SeñOr (just like str.title() )

The only way to fix this behaviour has been to set:

```
titlecase.set_small_word_list('')
```

But this defeats the purpose of the small word list.

Thank you!

**Comment by ppannuto** [comment]
I think this issue comes from the current regexes not handling unicode characters correctly. Happy to take a PR to fix!

**Comment by AlejandroFrias** [comment]
Side note on this, titles are generally treated differently in Spanish than English. Spanish title case rules are to only capitalize the first word, proper nouns, and acronyms (http://www.elearnspanishlanguage.com/grammar/capitalization.html). Everything else is lower case. So using `titlecase` on a Spanish title is probably not the way to go.

That being said, you should still fix the regexes to handle unicode characters. There are some English words (like resumé) that use them. And I could see use for a Spanglish title that wants to follow English title case rules but has a few Spanish words in them.

**Comment by Garrett-R** [comment]
I can't reproduce this problem.  What's the problem that occurs with unicode but doesn't without unicode?

```python
ipdb> titlecase('this is my resumé')
'This Is My Resumé'
ipdb> titlecase('Señor')
'Señor'
```

**Comment by ppannuto** [comment]
Looks like @Garrett-R has resolved this issue (thanks!). If there's still a problem, feel free to re-open this issue with other examples that don't work, or file a new issue.
