### ISSUE TITLE
Mistakenly captalizes second letter in words that start with a number

### ISSUE THREAD

**Issue by roemhildtg** [ppannuto/python-titlecase#18]
Example: `4th` becomes `4Th` and `1st` becomes `1St`

**Comment by ppannuto** [comment]
Yeah, the challenge with this library is that it's all regex based, so more cases do crop up. It takes some thinking to fix things like this and it's pretty low on my stack. I'll try to look at it at some point, but a PR that fixes would be awesome.

**Comment by AlejandroFrias** [comment]
Is this still a problem? This might have gotten resolved already...

**Comment by ppannuto** [comment]
Yeah.. given that https://github.com/ppannuto/python-titlecase/blob/9419f4326bedc85365eab7f243a43603786768f9/titlecase/tests.py#L28 passes, I'm going to close this as fixed.

If you're still having problems, feel free to re-open this issue.
