### ISSUE TITLE
Provide a small cli script to titlecase inputs?

### ISSUE THREAD

**Issue by Naereen** [ppannuto/python-titlecase#20]
Hi,
It could be helpful to add a small script to this project, maybe called `titlecase`, which basically would put its entries to titlecase:
```
$ titlecase "this is the name of an article.pdf"
This Is the Name of an Article.pdf
```

## A small python script?
```python
from sys import argv
from titlecase import titlecase
if __name__ == '__main__':
    for v in argv[1:]:
        print(titlecase(v))
```
Of course, it could be improved with a documentation, command line arguments etc. (I would suggest using [docopt](https://github.com/docopt/docopt)).

## Or a bash alias?
For instance, I just added [this alias](https://bitbucket.org/lbesson/bin/src/master/.bash_aliases#cl-570) to my Bash profile, and it works fine:
```bash
alias titlecase="python -c \"from sys import argv; from titlecase import titlecase; print(titlecase('\n'.join(argv[1:])))\""
```

**Comment by ppannuto** [comment]
Sure! The normal way to do this in Python is with entry points, i.e. something like this in setup.py:

```
        'entry_points': {
            'console_scripts': [
                'titlecase = titlecase:cmd',
                ],
            },
```

where `cmd` is a function that's added to titlecase that handle command line parsing. I'm pretty under water with other stuff the next few weeks, but happy to look into this eventually or to take a PR that add support.

**Comment by Naereen** [comment]
OK. I will try to provide a PR as soon as possible.
