### ISSUE TITLE
Doesn't Handle AT&T Properly

### ISSUE THREAD

**Issue by stampedeboss** [ppannuto/python-titlecase#22]
Even with the callback, always converts it to At&T.

**Comment by ppannuto** [comment]
Yeah, the challenge with this library is that it's all regex based, so more cases do crop up. It takes some thinking to fix things like this and it's pretty low on my stack. I'll try to look at it at some point, but a PR that fixes would be awesome.

**Comment by AlejandroFrias** [comment]
So this happens because SMALL_FIRST will match on AT&T because the "&" is apparently considered punctuation and "at" is a small word. Any good reason to work around that or can we just remove the "&" from `PUNCT`?

**Comment by ppannuto** [comment]
If that works, feels like a fine solution to me

**Comment by AlejandroFrias** [comment]
Nvm, that doesn't work. SMALL_FIRST still matches on "at&t" because the word break `\b` is recognized on the "&"...I'll have to think about it a bit...

**Comment by ppannuto** [comment]
Resolved by @AlejandroFrias in #24 -- thanks!
