### ISSUE TITLE
Spaces Are Treated As Words

### ISSUE THREAD

**Issue by ghost** [ppannuto/python-titlecase#30]
It seems if a string begins with a space titlecase will treat that space as the first word in the title.  For example, ' to turn a tide' will end up ' to Turn a Tide' instead of ' To Turn a Tide'.

**Comment by ppannuto** [comment]
I spent a few minutes futzing with this, but I think I'm inclined to leave this as it is. It's not that spaces are treated as words, rather it's that if there are leading spaces, the first word isn't special-cased, so the "small words" rules come into play, i.e.:

    $ titlecase ' to turn a tide'
     to Turn a Tide
    $ titlecase ' now turn a tide'
     Now Turn a Tide

It feels to me that leading whitespace is a bit odd to pass into this library in the first place, but if you did, it would most likely be in service of some form of partial string titlecasing, in which case you probably don't want to capitalize leading small words.

I don't feel strongly about this and would be open to arguments to change behavior if there were some good examples for when you'd titlecase strings with leading whitespace, but not strip it, and want the first characters capitalized.
