### ISSUE TITLE
Capitalisation only working for standard ASCII characters

### ISSUE THREAD

**Issue by dwaynebailey** [ppannuto/python-titlecase#33]
The characters outside of the first 127 bytes in UTF8 cannot be correctly capitalisable.

```
$ titlecase YAE NO
Yae No

$ titlecase ÝÆ ÑØ
ýæ ñø
```

The same applies to lowercase example, the first letters won't be capitalised.

These characters are taken from Latin1 range of Unicode, so characters most likely to have occurred in European languages.  Further testing on 'Latin Extended Additional' characters also shows this issue.

The following diff shows this within the test framework.

```diff
diff --git a/titlecase/tests.py b/titlecase/tests.py
index daee927..05698bd 100644
--- a/titlecase/tests.py
+++ b/titlecase/tests.py
@@ -259,6 +259,22 @@ TEST_DATA = (
     (
         "‘QUOTE’ A GREAT",
         "‘Quote’ a Great",
+    ),
+    (
+        "YEA NO",
+        "Yea No",
+    ),
+    (
+        "ÝÆ ÑØ",
+        "Ýæ Ñø",
+    ),
+    (
+        "yea no",
+        "Yea No",
+    ),
+    (
+        "ýæ ñø",
+        "Ýæ Ñø",
     )
 )
```

**Comment by ppannuto** [comment]
Unfortunately this is something of a known shortcoming for the regex-based approach used here. I don't really know the best way to generalize beyond English (another issue cropped up a little while about differing titlecasing rules for Spanish independent of characters used that's also unsolved).

I'm happy to take a PR or talk through possible architectures if you have suggestions.

**Comment by dwaynebailey** [comment]
Just adding some notes here:

* https://pypi.python.org/pypi/regex - might be an option as you can search for unicode properties, I assume you could search for characters that are LC or UC.
