### ISSUE TITLE
Title is not handling all scenarios

### ISSUE THREAD

**Issue by gaurav294** [ppannuto/python-titlecase#34]
If user need to convert some words like aBBCd,TestNG then title case is not handling it properly.

Actual output
title(TestNG)-> Testng
title(aBBCd) -> Abbcd

Expected output
title(TestNG)-> TestNG
title(aBBCd) -> ABBCd

**Comment by ppannuto** [comment]
Hmm... I'm not sure I can quite replicate your results:

```
$ python3
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from titlecase import titlecase
>>> titlecase('TestNG')
'TestNG'
>>> titlecase('aBBCd')
'aBBCd'
```

For `TestNG` it looks like it's already doing the right thing.

For `aBBCd`, I don't think I agree with your expected output. I think `aBBCd` is the correct output here. For the same reason that it doesn't touch the capitalization of `testNG` or `TestNG`, when there is a word with mixed case, the best guess is that it's a product or title of some kind, and to leave it as-is.

**Comment by bbpatel2001** [comment]
what about iPhone and hubSpot?

**Comment by ppannuto** [comment]
Those also behave as I would expect:

```
$ python3
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import titlecase as t
>>> t.titlecase('iPhone')
'iPhone'
>>> t.titlecase('hubSpot')
'hubSpot'
```

**Comment by ppannuto** [comment]
It looks like you're implementing something similar for https://github.com/robotframework/robotframework/pull/2719

As robotframework looks to be written in Python, it should be relatively easy to just use this library directly. This library has collected a bunch of special cases over time - if you look at the internals, titlecasing is unfortunately somewhat complex and requires lots of regexes to cover all the cases. I wouldn't recommend re-implementing from scratch unless you have a compelling reason.
