### ISSUE TITLE
Roman numerals shouldn't be titled

### ISSUE THREAD

**Issue by dwaynebailey** [ppannuto/python-titlecase#36]
E.g.

```
titlecase KING HENRY VIII
King Henry Viii
```
```
titelcase WORLD WAR II
World War Ii
```

Should be rendered as:
King Henry VIII
World War II

**Comment by Phyks** [comment]
That's a weird behavior:

```
>>> titlecase.titlecase("WORLD WAR II")
u'World War Ii'
>>> titlecase.titlecase("World war II")
u'World War II'
```

I guess this can be solved through `abbreviations` and https://gist.github.com/riverrun/ac91218bb1678b857c12#file-roman_numerals-py-L41-L46.

**Comment by ppannuto** [comment]
Probably won't have time to integrate this for a while. Happy to take a PR to fix.

Should probably pay some consideration to overlap between roman numerals and words, e.g. "id" is 499.., not sure what's best to do there, maybe just reason through the common overlaps and special-case them as they're more likely to be words?

**Comment by Phyks** [comment]
Yes, roman litterals are quite difficult to deal with as they overlap with the alphabet. :/ Not sure I can make a PR to handle them correctly, I was mostly mentionning it as a quick and dirty workaround (far from perfect) for original poster :)

**Comment by ppannuto** [comment]
Closing as stale. Feel free to re-open if needed.
