### ISSUE TITLE
Callback won't convert if words in bracket or quotation

### ISSUE THREAD

**Issue by dmkx** [ppannuto/python-titlecase#38]
```
def abbreviations(word, **kwargs):
    if word.upper() in ('ESD','HDD'):
        return word.upper()

titlecase('(esd) "hdd"',callback=abbreviations)
```
output: `(Esd) "Hdd"`

Is possible to ignore non-letter when convert words that list in callback function.

**Comment by ppannuto** [comment]
Not presently unfortunately. The callback is currently triggered just after the basic whitespace word split. This could possibly be refactored to be called with some awareness of punctuation, but that's a more substantial change. In the short term, it will probably be easiest to handle the punctuation case in your callback.

If you see a better solution, happy to take a PR.

**Comment by ppannuto** [comment]
Closing as stale. Feel free to re-open if needed.
