### ISSUE TITLE
All caps words are converted to mixed case

### ISSUE THREAD

**Issue by jrbray1** [ppannuto/python-titlecase#39]
All caps words, often acronyms, are converted to mixed case, so NASA becomes Nasa. They should remain unchanged, as words with embedded capitals, like GoH, are

**Comment by ppannuto** [comment]
Unfortunately, you start to run into tricky heuristics here. The assumption the library currently makes is that if a whole sentence is capitalized, then the whole thing should be titlecased. This will catch one-word examples incorrectly:

```
$ titlecase this should be fixed up
This Should Be Fixed Up
$ titlecase THIS SHOULD BE FIXED UP TOO
This Should Be Fixed Up Too
$ titlecase NASA
Nasa
$ titlecase Welcome to NASA
Welcome to NASA
$ titlecase WELCOME TO NASA
Welcome to Nasa
```

It's not clear to me in the one-word case how to know whether to treat it as "single word to be titlecased" or as an acronym. With the current behavior, you can always use `abbreviations` to add a custom list of acronyms that are useful in your dataset.

I'm open to suggestions if you have ideas on how to handle this ambiguity better.

**Comment by jrbray1** [comment]
This is a deal-breaker for my use of the library, I have some 30000 pages in a wiki I'm porting from case insensitive wikidot to case sensitive mediawiki, and was hoping titlecase would resolve the mess. There are at least 400 acronyms in use, probably many more, so a custom list would be very hard. I don't have all caps sentences, so if you could point me to the point in the code where the assumption is made I could invert it, and assume ALL CAPS would be left alone.

As this is a one-off import, I'm happy to hack the code around, but I'm no python expert.

I suppose I could do a workaround, appending sacrificial text to every line I convert "NASA waffle", would that cause any problems?

**Comment by ppannuto** [comment]
Hah, "NASA waffle" should work :) 

Or you should be able to just add an unconditional `continue` inside this `if` statement: https://github.com/ppannuto/python-titlecase/blob/master/titlecase/__init__.py#L93

**Comment by jrbray1** [comment]
I went down the Waffle route. I did find that roman numeral 'V' was changed to 'v'. Not sure you want to do that, as either use equally likely.

Thanks for your help anyway.

John

**Comment by ppannuto** [comment]
Yeah, #36 is exactly the Roman numeral problem.. not suffers from the same uncertainty. 

Given the waffle workaround, I’m going to close this issue. Feel free to reopen if merited.
