### ISSUE TITLE
Robot Framework

### ISSUE THREAD

**Issue by kenlyle2** [ppannuto/python-titlecase#41]
The String Libraary for Robot Framework is currently missing titlecase functionality.  Could a How To for calling titlecase from RF possibly be added to the Readme?

**Comment by ppannuto** [comment]
I think that sounds like something that would be more appropriate to add to the readme of the Sting Library / the Robot Framework—we can’t maintain integration guides for every project.

**Comment by kenlyle2** [comment]
Right, Pat.  It's kind of a temporay workaround, until the String Libary gets fixed...and it seems like that will be a while, because those guys don't seem to be thinking incremental and agile...introducing issues like multiple languages, etc.  In my RF project as a workaround, I had to lowercase an uppercase article title, split the words, and then uppercase the first letter and append it back using substring funcitons.  Pretty ugly.
