### ISSUE TITLE
Callback word is always marked immutable when altered.

### ISSUE THREAD

**Issue by Polymuter** [ppannuto/python-titlecase#42]
Shouldn't the callback word still follow some of the basic principals of title capitalization?  Such as the first and last words always being capitalized?

**Comment by ppannuto** [comment]
The assumption is that callbacks are authoritative, for example, something like `AT&T` from #22 or the `uDMA` product are names and always capitalized exactly as such, regardless of position.

Is there an example of when a custom callback would want something to further modify the word?

**Comment by Polymuter** [comment]
I was trying to keep the ebonic forms of some coordinating conjunctions lowercased.  I was a little confused at first but after re-reading the code I appended them to the small word list.

It does makes sense to always mark some words immutable.  However, it would be nice to do that conditionally within the callback.
