### ISSUE TITLE
setup.py: The ‘regex’ package does not get automatically installed as a dependency

### ISSUE THREAD

**Issue by iburago** [ppannuto/python-titlecase#56]
If the `regex` package is not installed on the user’s system, the
current `setup.py` file does not install it automatically, causing
the `ModuleNotFoundError` exception in any module importing
`titlecase`:

```
Traceback (most recent call last):
  …
  File "/Users/ib/Library/Python/3.7/lib/python/site-packages/titlecase/__init__.py", line 16, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
```

This is due to `regex` being [listed in the `setup_requires`
argument in the `setup` call][sr] only, and not being listed
in the `install_requires` one.

[sr]: https://github.com/ppannuto/python-titlecase/blob/cf59b1f2ee85ea4b8926f99928123a1a7eb34526/setup.py#L49

The issue can be resolved by adding the following argument
to the `setup()` call:

	    install_requires=['regex>=2020.4.4'],

We should be aware that this exposes a [known issue with
setuptools][st-issue] when the same package is listed both in
`setup_requires` and `install_requires`. However this only
applies to the cases when the `setup.py` is invoked manually.

It is my understanding that when the package is installed via
`pip install`, everything works correctly. Given that, I think,
the tradeoff in adding `regex` to `install_requires` is well
justified (especially given that [the setuptools issue][st-issue] will hopefully
be addressed in the future—if not already).

[st-issue]: https://github.com/pypa/setuptools/issues/391

**Comment by iburago** [comment]
Actually, do we need the `regex` module to be present during setup?
Perhaps I am missing something, but I cannot see any reason why
it is necessary to have `setup_requires` at all.

**Comment by ppannuto** [comment]
Prior to the version fix, because it was imported in setup, it was needed in setup. I'm *guessing* way back in the day, setup ran before install and so things used to work.

I'll update this to move to install.

**Comment by iburago** [comment]
Sounds good.
