### ISSUE TITLE
regex package dependency not installed on 0.13 release

### ISSUE THREAD

**Issue by nishkala** [ppannuto/python-titlecase#61]
Could the fix for https://github.com/ppannuto/python-titlecase/issues/56 be applied to the 0.13 package?

**Comment by ppannuto** [comment]
I'm not sure I understand the question?

Pip packages are immutable, so there's no way to change the 0.13 release I'm afraid. Upgrading to a newer version however, should be an easy fix.

**Comment by nishkala** [comment]
Sorry, that was phrased badly. I was hoping for a 0.13.1 release with the version of `regex` installed for Python 2.  I cannot upgrade to the newest working version as it doesn't support Python 2.

**Comment by ppannuto** [comment]
As the package is pretty much useless without this, I went ahead and pushed a 0.13.1 ( https://pypi.org/project/titlecase/0.13.1/ )

However, to be clear: I have negative interest in supporting Py2k. It's been scheduled to be deprecated for a decade, and now is firmly in the rear-view mirror. I will not be backporting things for Py2k generally.
