### ISSUE TITLE
Random short words seem to be all-capitalized, why?

### ISSUE THREAD

**Issue by ses4j** [ppannuto/python-titlecase#68]
Why are PCL BCL and BCT made into all-caps when I run this:

    > titlecase('pca pcl bcl acl bct')
    'Pca PCL BCL Acl BCT'

I have no external wordlist file that I'm aware of.

**Comment by ppannuto** [comment]
I believe that's tripping the heuristic that a string of all consonants is most likely an acronym, and therefore should be capitalized.

**Comment by ppannuto** [comment]
Closing I don't think there's an actual issue here -- feel free to re-open if appropriate.

**Comment by ses4j** [comment]
I see.  That makes sense, but also that seems like a heuristic that will cause more harm than good.  Can it be controlled or disabled?  Maybe documented?  The README says "The filter employs some heuristics to guess abbreviations that don't need conversion." but this is guessing acronyms that do, which is different and causes us quite a bit of trouble.

**Comment by ppannuto** [comment]
At the end of the day, a regex+huersitics-based approach is always going to be imperfect. The wordlist feature should hopefully produce a reasonable escape-hatch for domain specific acronyms.
