### ISSUE TITLE
No Changelog?

### ISSUE THREAD

**Issue by MinchinWeb** [ppannuto/python-titlecase#69]
I'm looking to update this library inside one of my projects (from v0.12.0 to 1.1.1 in this case), but I can't seem to find a changelog. A changelog is helpful in trying to figure out if an update will break my project.

Can you point me to the changelog, if there is one? If one does not exist, would you consider keeping one for future releases?

Thanks for creating this library!

**Comment by ppannuto** [comment]
The text in each release tag collectively forms a pretty good changelog:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/339422/89410268-6816ab80-d6f1-11ea-8b8d-34c5669f5aa0.png">

There isn't a standalone one at the moment, though adding one would probably be reasonable.

**Comment by ppannuto** [comment]
Thinking more, the github releases are a good changelog. And I'd rather not duplicate information in two places. I'm going to close this.
