### ISSUE TITLE
Making available on conda-forge

### ISSUE THREAD

**Issue by brocksam** [ppannuto/python-titlecase#70]
I'm using *titlecase* on a number of my own projects which I'd now like to make available on conda-forge as well as PyPI. I'm currently stuck in doing this because having a dependency that isn't available itself on conda-forge blocks the build process. I'd like *titlecase* to be available on conda-forge.

I'll put together the recipe and PR for the `conda-forge/titlecase-feedstock`. This is to check:

1. Are the creators/maintainers happy for me to do this?
2. Which maintainers (if any) would like to be recipe maintainers?

Thanks for making a really useful tool!

**Comment by ppannuto** [comment]
I've never heard of conda-forge. This library is pretty-much maintenance mode only, so if you're willing to maintain the conda-forge related stuff and it doesn't otherwise affect things, that's fine by me. You should list yourself as the recipe maintainer on conda-forge, as I'm unlikely to do anything with it.

**Comment by brocksam** [comment]
*conda-forge* is a little bit like *PyPI* is to *pip*, only it's for the package manager *conda* (https://docs.conda.io/en/latest/) which is typically much better a resolving dependencies between installed packages in a virtual environment than *pip* and is heavily used by the scientific Python community. Thanks for the approval, I'm happy to maintain the conda-feedstock alone (which will be a minimal job if *titlecase* is in maintenance-only mode and therefore won't be updating regularly on *PyPI*). The *conda-forge* stuff is managed completely separately some won't impact this repo at all.

**Comment by ppannuto** [comment]
Sounds good. I'm going to close this issue as effectively resolved, feel free to re-open if needed for any reason.

**Comment by brocksam** [comment]
No problem, thanks. I'll submit a PR in due course amending the README with additional instructions of how to install using *conda* in addition to *pip*.
