### ISSUE TITLE
version confusion, 0.13.1 containing newer code compared to 1.1.1

### ISSUE THREAD

**Issue by valentijnscholten** [ppannuto/python-titlecase#72]
I was waiting for #60 to become released to get rid of all the log messages. Looking at that PR it seems merged and released. However we are on the latest release `1.1.1` and the issue is still there.

Looking at the commit history it _looks_ like 0.13.1 contains the fix and was released _after_ `1.1.1`?

We're using dependabot and renovate to stay up-to-date and they are not reporting when 0.13.1 was released, nor will they alert us on any 0.x release as 1.1.1 is newer according to semver (or a different major version alltogether).

What is the recommended version to run?

**Comment by valentijnscholten** [comment]
after reading some more I see that 1.0 dropped python2 support and 1.1.1 _should_ be identical to 0.13.1.
but it isn't :-) The changes from #60 are missing in 1.1.1: https://github.com/ppannuto/python-titlecase/blob/v1.1.1/titlecase/__init__.py

**Comment by ppannuto** [comment]
#60 is not in any released version, there are number of patches in main that have not yet been pushed out to any release:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/339422/96351330-76793000-106f-11eb-9871-274cf2f1eb1c.png">

I'd deferred a release a @iburago mentioned there was some more stuff to come; though perhaps the time has come to just do a release.

**Comment by brunobg** [comment]
Yes, +1 for a new release.

**Comment by ppannuto** [comment]
Pushed v2.0 to PyPI
