### ISSUE TITLE
Tries to open .titlecase when running in an egg

### ISSUE THREAD

**Issue by brunobg** [ppannuto/python-titlecase#73]
I'm using this as part of an egg, and it tries to open the .titlecase file. Anyway to force this not to happen?

**Comment by ppannuto** [comment]
Python packaging remains the most opaque and confusing process to me. I have no idea what it means to use something as 'part of an egg' I'm afraid. I did just push some updates that limit the cases where customization are used by default, perhaps that will address your needs?

Failing that, I'm happy to take a PR.

**Comment by brunobg** [comment]
I'm not sure why this happens. I ended up forking this because the log calls were messing up with my logs and I needed a few customizations that wouldn't be useful for most people. My suggestion is that you add a flag so users can override the .titlecase access, or separate the cli version into a different module.
