### ISSUE TITLE
Allow use of stdlib "re" package as an alternative to regex

### ISSUE THREAD

**Issue by rkhwaja** [ppannuto/python-titlecase#75]
It would make the install pure python, particularly relevant right now for me because it won't install on macos arm64 since regex doesn't have a wheel for this architecture.

**Comment by ppannuto** [comment]
Not sure I know enough to know if there are any meaningful difference between 're' and 'regex' -- have to take a PR that makes the switch; if the test cases pass, I'll merge it.

**Comment by rkhwaja** [comment]
Fixed by https://github.com/ppannuto/python-titlecase/pull/76

**Comment by rkhwaja** [comment]
My solution doesn't work.

It throws ImportError if the wrong arch regex is installed:
Traceback (most recent call last):
```ImportError: dlopen(/.../python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/.../python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
	/.../python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
```

It throws ModuleNotFoundError if regex isn't installed:
```  File "/.../python3.9/site-packages/titlecase/__init__.py", line 18, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
```

*However*, even though ModuleNotFoundError is a subclass of ImportError, the
```
catch ImportError:
```
line in __init__.py isn't just catching the error and running the exception handler. I'm not sure why, I've used this pattern lots of times before but nevertheless it's not working.

**Comment by rkhwaja** [comment]
Doesn't work. I get an error on the following line:
```INLINE_PERIOD = re.compile(r'[\p{Letter}][.][\p{Letter}]')```

**Comment by ppannuto** [comment]
I think my answer is the same as before: Happy to take a PR to fix, and I guess also a test case that validates that `re` is being used as expected on the platforms where you're having issues. The `regex` vs `re` thing doesn't affect any of the setups I own, so it's hard for me to test/debug/fix.

**Comment by ppannuto** [comment]
I believe this should now be fixed. Please re-open if there are remaining issues.
