### ISSUE TITLE
Titles that are ALMOST all caps

### ISSUE THREAD

**Issue by theconor** [ppannuto/python-titlecase#8]
This is a good module.  I've run across a problem with titles that are ALMOST all caps -- these don't get converted properly, presumably because we otherwise want to preserve CAPS words in other mixed-case text.   Note the same problem also occurs with accented uppercase letters (these don't get recognised as ALL-CAPS).

e.g.

> > > titlecase( 'a gentleman and a thief' )
> > > 'A Gentleman and a Thief'                                      [good]
> > > titlecase( 'A GENTLEMAN AND A THIEF' )
> > > 'A Gentleman and a Thief'                                      [good]
> > > titlecase( 'A GENTLEMAN AND a THIEF' )
> > > 'A GENTLEMAN AND a THIEF'                              [not so good]
> > > titlecase( 'A GENTLEMAN AND Â THIEF' )
> > > 'A GENTLEMAN AND \xc3\x82 THIEF'                   [not so good]
> > > titlecase( 'A gentleman and a THIEF' )
> > > 'A Gentleman and a THIEF'                                    [possibly good]

Note I've worked round this by converting everything to uppercase and stripping non-ascii first, but would be good to have the module handle it directly, if possible.

**Comment by ppannuto** [comment]
Ultimately, there are always going to be some heuristics at play. One heuristic is that if a line has a mixture of all-caps and not all-caps words, then the all-caps words should be left alone. The example `A GENTLEMAN AND a THIEF` fits this heuristic. Given that input I'm not actually sure what output you would expect. It fits the same category as your last example.

The other "not so good" I believe is a Python2 unicode anachronism, observe:

```
$ python2
>>>  titlecase('A GENTLEMAN AND Â THIEF')
'A GENTLEMAN AND \xc3\x82 THIEF'
>>> titlecase('A GENTLEMAN AND Â THIEF') == 'A GENTLEMAN AND Â THIEF'
True

$ python3
>>> titlecase('A GENTLEMAN AND Â THIEF')
'A GENTLEMAN AND Â THIEF'
>>> titlecase('A GENTLEMAN AND Â THIEF') == 'A GENTLEMAN AND Â THIEF'
True
```

If you have to deal with Unicode, I'd strongly advise moving to Python3.

**Comment by theconor** [comment]
I agree with the heuristics.  The one I've used as a workaround is to first check whether the title does NOT contain r'[a-z]{4,}' -- i.e. a softer alternative to ALL_CAPS that works better with my data, which has accented characters and some unicode punctuation that caused problems previously.
 
You're right I should move to Python 3, I intend to do this.  But shouldn't the correct result to the example be:
>>> titlecase('A GENTLEMAN AND Â THIEF')
'A Gentleman and â Thief'    [Titlecase]

(i.e. The accented character treated as a normal character?  Note I am pretty new to Python so don't know how feasible this might be.)

**Comment by ppannuto** [comment]
The `\x` is a unicode escape in Python.

`\xc3` is [latin capital letter a with tilde](http://unicodelookup.com/#0xc3/1)
`\x82` is [break permitted here](http://unicodelookup.com/#0x82/1)

That's why the strings are equal. You can coerce Python2 to print the unicode correctly somehow, but the right choice is really just to move to Py3k.

**Comment by theconor** [comment]
Just to be clear, the point I am making is that regardless of the unicode issues, I'd prefer the output to be in Titlecase rather than ALL CAPS.  (Especially if \xc3 is regarded as an uppercase letter, and \x82 is non-printing.)

Thanks for the info.

**Comment by ppannuto** [comment]
Closing in favor of #33 to track.

**Comment by 1kastner** [comment]
Could this be added to the readme?

**Comment by ppannuto** [comment]
I added some limitations text in 4aa3ad4, if you had something more / else in mind, please send a PR

**Comment by 1kastner** [comment]
I did in #51
