### ISSUE TITLE
Preserving white space

### ISSUE THREAD

**Issue by dukeEllington32** [ppannuto/python-titlecase#88]
When I use the following shell command, the _outfile_ removes all lines that don't contain text.

`$ titlecase -f infile -o outfile`

Is there a way to preserve all white space?

**Comment by ppannuto** [comment]
_Sigh._ I need to fix the testing infrastructure, as `nose` is apparently deprecated. I'll put out a release whenever I have time to get that fixed as well. This does work locally when running these tests with old python's still supported by `nose`. As long as you don't need to run tests, you can run off git tip for the short term.
