### ISSUE TITLE
Callback with hyphenated uppercase words

### ISSUE THREAD

**Issue by theconor** [ppannuto/python-titlecase#9]
Not sure if this is a problem, or just the way I'm using it.

I have strings that are mostly uppercase letters, but with occasional lowercase codes that I want to preserve.  e.g. "DEPARTMENT FOR TRANSPORT (DfT)".

So I created a callback that scanned for lowercase characters (and numbers) in the otherwise uppercase text.  This worked fine, but the problem occurs when there are hyphenated words in the input title. e.g. "RED-BLACK NEWSPAPER TITLE".  This gets passed to the callback as "RED-BLACK", then "red" (lowercase), then "black" (lowercase), and because of my logic checking for lowercase letters, I end up with "red/black Newspaper Title".

Again, I've got a workaround for this so not a big problem, but would there be a way of NOT applying lower() to words when they go through the splitter?

**Comment by ppannuto** [comment]
This is a good point. See if the fix on the issue-9 branch solves this for you.

**Comment by theconor** [comment]
Thank you, I have tried this on my data and it works nicely.  Thanks for the quick response.
