### ISSUE TITLE
Initial words in all caps are sometimes not cased properly

### ISSUE THREAD

**Issue by rogerl50** [ppannuto/python-titlecase#90]
`titlecase('FOO bar')` returns `FOO Bar`, while `titlecase('FOO BAR')` returns `Foo Bar`.

**Comment by ppannuto** [comment]
This is by design. If a string is all caps (or all lowercase), it is assumed there is no intentional casing and it is titlecased as such. If there is already mixed case and a word is all uppercase, it is assumed that word is an acronym, and it is left unchanged.
