### ISSUE TITLE
cli pipe titlecase to chapters for filenames

### ISSUE THREAD

**Issue by mrfragger** [ppannuto/python-titlecase#91]
I used titlecase before for chapters for audiobooks by putting them into a text file.  Here's the command I use now.  Took me a long time to figure out the proper syntax so hope it saves some time attempting to do that same.
`for f in *.opus ; do mv -i -- "$f" "$(printf '%s\n' "$f" | titlecase)"`

**Comment by ppannuto** [comment]
Thanks for the example – don't think think there's an 'issue' here per se, so I'm going to close this, but should remain available in the archives for folks to find.
