### ISSUE TITLE
chicago cmos style?

### ISSUE THREAD

**Issue by kevinlawler** [ppannuto/python-titlecase#98]
any chance?

**Comment by alerque** [comment]
Somebody is on a quest for title casing ;-) Since you posted issues there too I assume you've seen my [decasify](https://github.com/alerque/decasify) project that can also be used as a Python module if desired. It has partial support for the CMOS guidelines (and PRs to catch punctuation edge cases for more full support are welcome).

**Comment by kevinlawler** [comment]
Yes, it's wild but I suppose ultimately unsurprising that nobody has built a thing that's `{cmos, nyt, ap, ...} x {en, sp, fr, tr, ...} x {cli, lib, unixtool} x ...` that is actively maintained. If they can do it for timezones, they can do it for this (right?). The best logic seems to live behind a paywalled API which is ridiculous to me.

This space is littered with also-rans. I am following the path of least resistance to get my problems solved. Yours seems like the leading candidate but I might as well kick this hive and see what buzzes out. I seem to find new projects every time I look.

**Comment by alerque** [comment]
I assume part of the reason it hasn't been fully implemented is some of the style guide are ... more like guidelines really. They leave quite a bit on the table at editor discretion — which does not lend itself to programmatic applications. I think that's one reason you'll find the Grubber/DaringFireball rules implemented in more libraries: they are closer to deterministic than most other EN style guides.

Another factor is that until recently it hasn't really been possible to address the language ecosystem problem using one code base to effectively serve multiple languages. The binding situation has improved in many ecosystems now and especially using Rust as a base it is surprisingly easy to get Python/Lua/Javascript/whatever else bindings that work at native machine code efficiency.

**Comment by ppannuto** [comment]
Yeah, @alerque has hit the essence of things here. I maintain this library as a convenience for those who just want a minimum viable something (and who keep stumbling across the old blog post full of perl scripts :) ), but it's not trying to be any more than a basic regex engine [see the Limitations on the main README].

If you've got the time to implement anything better, pull requests are welcome, but I don't even know what cmos style is :).
